### ISSUE TITLE
Project Site Feedback 

### ISSUE THREAD

**Issue by asuljic1** [nini3423/Project#2]
Hey, I really liked what you have going with the website. Some things that I would change is the centering on the table of the home page. Also you might want to play around with different header colors I feel like this one takes away from your content. I know this is only the first draft of the site but you could try to make the landing an area where people instantly know what your site will be about, I know from personal experience this can help lower bounce rate. Overall great work and good luck with your project! :)

**Comment by nini3423** [comment]
Thank you for your feedback, when you say centering on the table, what do you mean by that?
